### ISSUE TITLE
Is there a way to generate a PDF from the questionnaire?

### ISSUE THREAD

**Issue by aurelien-bernard** [luis901101/fhir_questionnaire#11]
I'm wondering how to generate a PDF file from a FHIR questionnaire. I'm looking for a server solution and not a flutter2PDF :)

**Comment by luis901101** [comment]
This is a question more for StackOverflow/ChatGPT than an issue of this flutter package.

**Comment by aurelien-bernard** [comment]
Sorry to have bothered you! As you may have come across the problem yourself, I was wondering if you'd found a solution.

**Comment by luis901101** [comment]
No bother, I just pointed this is not the place to ask because this is a specific package for a specific use case, which is basically rendering a Questionnaire and generate the response and also I have not had the necessity of generating a PDF from a Questionnaire. 
As far as I know, FHIR doesn't provide this so it must be implemented, if you are considering for a sever side solution you should check for libraries or something available for the tech you choose for your server.
